/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkhaus;

/**
 *
 * @author ForouzanShebli
 */
public class ParkInfo extends javax.swing.JDialog {
      //Attribute
      private Main master = null;
      /**
       * Creates new form ParkInfo
       */
      public ParkInfo(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            master = (Main)parent;
      }
      public void refresh(Parkitem[] array){
            this.lpKfz.setListData(array);
      }
      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT
       * modify this code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jScrollPane1 = new javax.swing.JScrollPane();
            lpKfz = new javax.swing.JList<>();
            btUse = new javax.swing.JButton();
            btClose = new javax.swing.JButton();
            lfTitel = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

            lpKfz.setModel(new Model() );
            jScrollPane1.setViewportView(lpKfz);

            btUse.setText("Übernehmen");
            btUse.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btUseActionPerformed(evt);
                  }
            });

            btClose.setText("Schließen");
            btClose.setMaximumSize(new java.awt.Dimension(105, 25));
            btClose.setMinimumSize(new java.awt.Dimension(105, 25));
            btClose.setPreferredSize(new java.awt.Dimension(105, 25));
            btClose.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btCloseActionPerformed(evt);
                  }
            });

            lfTitel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            lfTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lfTitel.setText("Aktuelle Parkhausbelegung");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(btUse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                              .addComponent(lfTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lfTitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(btUse)
                              .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents
      private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
            this.setVisible(false);
      }//GEN-LAST:event_btCloseActionPerformed
      private void btUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUseActionPerformed
            String kfzId = "";
        String so = "";
        // Selektiertes Objekt auswerten
        try {
        Parkitem temp = lpKfz.getSelectedValue();
        kfzId = temp.getKfz().getKfzId();// KFZ Kennzeichen ermitteln
        so = temp.getSo();               // KFZ Standort ermitteln
        } catch(Exception ex) {
            kfzId = "---";
            so = "Keine Auswahl";
        }
        master.setLfStandort(so);
        master.setTfKfzId(kfzId);
        this.setVisible(false);
      }//GEN-LAST:event_btUseActionPerformed
      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(ParkInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(ParkInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(ParkInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(ParkInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        ParkInfo dialog = new ParkInfo(new javax.swing.JFrame(), true);
                        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                              @Override
                              public void windowClosing(java.awt.event.WindowEvent e) {
                                    System.exit(0);
                              }
                        });
                        dialog.setVisible(true);
                  }
            });
      }
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btClose;
      private javax.swing.JButton btUse;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JLabel lfTitel;
      private javax.swing.JList<Parkitem> lpKfz;
      // End of variables declaration//GEN-END:variables
}
